In [14]:
# Phutharesuan Wachirapisut
# 651610348
# Lab05_02
# 229323 sec 002

In [15]:
import files
import pandas as pd
import io 
import os 
import csv
# uploaded=files.upload()
os.chdir("/Users/phutharesuanwachirapisut/Programming/Python/229323/Lab05")

In [16]:
df = pd.read_csv("data_651610348_0501.csv");df

FileNotFoundError: [Errno 2] No such file or directory: 'data_651610348_0501.csv'

In [ ]:
def BMI_caculate(height, weight):
    return round(weight/(height**2),4)

In [ ]:
df["BMI Value"] = BMI_caculate(height=df["Height(metre)"], weight=df["Weight(kg.)"])
df

      Name  Height(metre)  Weight(kg.)  BMI Value
0    นัทธี           1.71         62.5    21.3741
1     Adam           1.75         84.0    27.4286
2    Tommy           1.68         70.5    24.9787
3  สาวิตรี           1.52         46.0    19.9100
4  William           1.82         75.3    22.7328
5   ภาวิกา           1.73         65.4    21.8517
6      กมล           1.56         56.2    23.0934
7   Kristy           1.67         72.3    25.9242

In [ ]:
def BMI_mean(value):    
    if value <= 18.5:
        return "Thin" 
    elif 18.6 <= value and value <= 24.9:
        return "Healthy" 
    elif 25 <= value and value <= 29.9:
        return "Overweight" 
    elif value >= 30:
        return "Obese" 

df["Mean"] = df["BMI Value"].apply(BMI_mean)
df

      Name  Height(metre)  Weight(kg.)  BMI Value        Mean
0    นัทธี           1.71         62.5    21.3741     Healthy
1     Adam           1.75         84.0    27.4286  Overweight
2    Tommy           1.68         70.5    24.9787        None
3  สาวิตรี           1.52         46.0    19.9100     Healthy
4  William           1.82         75.3    22.7328     Healthy
5   ภาวิกา           1.73         65.4    21.8517     Healthy
6      กมล           1.56         56.2    23.0934     Healthy
7   Kristy           1.67         72.3    25.9242  Overweight

In [ ]:
data_list = list(df.itertuples(index=False,name=None))

result = open("data_651610348_0502.csv","w")
result = csv.writer(result)

result.writerow(["Name","Height(metre)","Weight(kg.)", "BMI Value", "Mean"])
for i in range(len(data_list)):
    result.writerow([data_list[i][0],data_list[i][1],data_list[i][2],data_list[i][3],data_list[i][4]])

In [ ]:
pd.read_csv("data_651610348_0502.csv")

      Name  Height(metre)  Weight(kg.)  BMI Value        Mean
0    นัทธี           1.71         62.5    21.3741     Healthy
1     Adam           1.75         84.0    27.4286  Overweight
2    Tommy           1.68         70.5    24.9787         NaN
3  สาวิตรี           1.52         46.0    19.9100     Healthy
4  William           1.82         75.3    22.7328     Healthy
5   ภาวิกา           1.73         65.4    21.8517     Healthy
6      กมล           1.56         56.2    23.0934     Healthy
7   Kristy           1.67         72.3    25.9242  Overweight